version: "3"

services:
  lamp:
    image: mattrayner/lamp:latest
    container_name: 'lamp'
    restart: 'always'
    ports:
      - "80:80"
      - "3306:3306"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/app
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
    environment:
      MYSQL_PASS: ${MYSQL_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - lamp
    environment:
      PMA_HOST: lamp
      PMA_PORT: 3306
    ports:
      - '81:80'
    volumes:
      - /sessions
  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "6379:6379"